name: Nodejs-Worker-Cloudflare

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.17.0 ]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g ipfs-deploy@10.1.1 --ignore-scripts
    - run: npm ci
    - run: npm run build --if-present
    - name: Publish Cloudflare Worker
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
